import type { ThemeDefinition, ThemeTokens } from "./types";

export const DEFAULT_THEME_ID = "default";

export const DEFAULT_THEME: ThemeDefinition = {
  id: DEFAULT_THEME_ID,
  name: "Default",
  description: "The built-in Ryco light & dark palette.",
  builtIn: true,
  light: {
    background: "var(--color-white)",
    "app-chrome-background": "var(--background)",
    foreground: "var(--color-neutral-800)",
    card: "var(--color-white)",
    "card-foreground": "var(--color-neutral-800)",
    popover: "var(--color-white)",
    "popover-foreground": "var(--color-neutral-800)",
    primary: "oklch(0.488 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-black) / 4%)",
    "secondary-foreground": "var(--color-neutral-800)",
    muted: "--alpha(var(--color-black) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-black))",
    accent: "--alpha(var(--color-black) / 4%)",
    "accent-foreground": "var(--color-neutral-800)",
    destructive: "var(--color-red-500)",
    "destructive-foreground": "var(--color-red-700)",
    border: "--alpha(var(--color-black) / 8%)",
    input: "--alpha(var(--color-black) / 10%)",
    ring: "oklch(0.488 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-700)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-700)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-700)",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.15)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.25)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.1)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.2)",
    "noise-opacity": "0.035",
  },
  dark: {
    background: "color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white))",
    "app-chrome-background": "var(--background)",
    foreground: "var(--color-neutral-100)",
    card: "color-mix(in srgb, var(--background) 98%, var(--color-white))",
    "card-foreground": "var(--color-neutral-100)",
    popover: "color-mix(in srgb, var(--background) 98%, var(--color-white))",
    "popover-foreground": "var(--color-neutral-100)",
    primary: "oklch(0.588 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-white) / 4%)",
    "secondary-foreground": "var(--color-neutral-100)",
    muted: "--alpha(var(--color-white) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-white))",
    accent: "--alpha(var(--color-white) / 4%)",
    "accent-foreground": "var(--color-neutral-100)",
    destructive: "color-mix(in srgb, var(--color-red-500) 90%, var(--color-white))",
    "destructive-foreground": "var(--color-red-400)",
    border: "--alpha(var(--color-white) / 6%)",
    input: "--alpha(var(--color-white) / 8%)",
    ring: "oklch(0.588 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-400)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-400)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-400)",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.1)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.18)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.08)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.15)",
  },
};

type PresetPalette = {
  background: string;
  chrome: string;
  foreground: string;
  card: string;
  popover?: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring?: string;
  info: string;
  success: string;
  warning: string;
  scrollbarForeground?: string;
};

function presetTokens(palette: PresetPalette): ThemeTokens {
  const scrollbarBase = palette.scrollbarForeground ?? palette.foreground;
  return {
    background: palette.background,
    "app-chrome-background": palette.chrome,
    foreground: palette.foreground,
    card: palette.card,
    "card-foreground": palette.foreground,
    popover: palette.popover ?? palette.card,
    "popover-foreground": palette.foreground,
    primary: palette.primary,
    "primary-foreground": palette.primaryForeground,
    secondary: palette.secondary,
    "secondary-foreground": palette.foreground,
    muted: palette.muted,
    "muted-foreground": palette.mutedForeground,
    accent: palette.accent,
    "accent-foreground": palette.accentForeground,
    destructive: palette.destructive,
    "destructive-foreground": palette.destructiveForeground,
    border: palette.border,
    input: palette.input,
    ring: palette.ring ?? palette.primary,
    info: palette.info,
    "info-foreground": palette.info,
    success: palette.success,
    "success-foreground": palette.success,
    warning: palette.warning,
    "warning-foreground": palette.warning,
    "scrollbar-thumb": hexToRgba(scrollbarBase, 0.18),
    "scrollbar-thumb-hover": hexToRgba(scrollbarBase, 0.32),
    "scrollbar-thumb-thin": hexToRgba(scrollbarBase, 0.12),
    "scrollbar-thumb-thin-hover": hexToRgba(scrollbarBase, 0.24),
  };
}

function hexToRgba(hex: string, alpha: number): string {
  const match = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!match || match[1] === undefined) return hex;
  const value = match[1];
  const r = Number.parseInt(value.slice(0, 2), 16);
  const g = Number.parseInt(value.slice(2, 4), 16);
  const b = Number.parseInt(value.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const SOLARIZED_DARK: ThemeDefinition = {
  id: "solarized-dark",
  name: "Solarized Dark",
  description: "Ethan Schoonover's iconic dark palette with warm beige accents.",
  builtIn: true,
  light: {
    background: "#fdf6e3",
    "app-chrome-background": "#fdf6e3",
    foreground: "#586e75",
    card: "#fdf6e3",
    "card-foreground": "#586e75",
    popover: "#eee8d5",
    "popover-foreground": "#586e75",
    primary: "#268bd2",
    "primary-foreground": "#fdf6e3",
    secondary: "#eee8d5",
    "secondary-foreground": "#586e75",
    muted: "#eee8d5",
    "muted-foreground": "#93a1a1",
    accent: "#eee8d5",
    "accent-foreground": "#586e75",
    destructive: "#dc322f",
    "destructive-foreground": "#fdf6e3",
    border: "rgba(88, 110, 117, 0.18)",
    input: "rgba(88, 110, 117, 0.22)",
    ring: "#268bd2",
    info: "#268bd2",
    "info-foreground": "#268bd2",
    success: "#859900",
    "success-foreground": "#859900",
    warning: "#b58900",
    "warning-foreground": "#b58900",
    "scrollbar-thumb": "rgba(88, 110, 117, 0.3)",
    "scrollbar-thumb-hover": "rgba(88, 110, 117, 0.45)",
    "scrollbar-thumb-thin": "rgba(88, 110, 117, 0.2)",
    "scrollbar-thumb-thin-hover": "rgba(88, 110, 117, 0.35)",
  },
  dark: {
    background: "#002b36",
    "app-chrome-background": "#002b36",
    foreground: "#93a1a1",
    card: "#073642",
    "card-foreground": "#93a1a1",
    popover: "#073642",
    "popover-foreground": "#93a1a1",
    primary: "#268bd2",
    "primary-foreground": "#002b36",
    secondary: "#073642",
    "secondary-foreground": "#93a1a1",
    muted: "#073642",
    "muted-foreground": "#657b83",
    accent: "#073642",
    "accent-foreground": "#eee8d5",
    destructive: "#dc322f",
    "destructive-foreground": "#fdf6e3",
    border: "rgba(147, 161, 161, 0.14)",
    input: "rgba(147, 161, 161, 0.18)",
    ring: "#268bd2",
    info: "#268bd2",
    "info-foreground": "#2aa198",
    success: "#859900",
    "success-foreground": "#859900",
    warning: "#b58900",
    "warning-foreground": "#b58900",
    "scrollbar-thumb": "rgba(147, 161, 161, 0.18)",
    "scrollbar-thumb-hover": "rgba(147, 161, 161, 0.32)",
    "scrollbar-thumb-thin": "rgba(147, 161, 161, 0.12)",
    "scrollbar-thumb-thin-hover": "rgba(147, 161, 161, 0.24)",
  },
};

const NORD: ThemeDefinition = {
  id: "nord",
  name: "Nord",
  description: "Cool arctic blues inspired by the Nord palette by Arctic Ice Studio.",
  builtIn: true,
  dark: {
    background: "#2e3440",
    "app-chrome-background": "#2e3440",
    foreground: "#d8dee9",
    card: "#3b4252",
    "card-foreground": "#e5e9f0",
    popover: "#3b4252",
    "popover-foreground": "#e5e9f0",
    primary: "#88c0d0",
    "primary-foreground": "#2e3440",
    secondary: "#434c5e",
    "secondary-foreground": "#e5e9f0",
    muted: "#3b4252",
    "muted-foreground": "#7b8794",
    accent: "#434c5e",
    "accent-foreground": "#eceff4",
    destructive: "#bf616a",
    "destructive-foreground": "#eceff4",
    border: "rgba(216, 222, 233, 0.1)",
    input: "rgba(216, 222, 233, 0.14)",
    ring: "#88c0d0",
    info: "#81a1c1",
    "info-foreground": "#8fbcbb",
    success: "#a3be8c",
    "success-foreground": "#a3be8c",
    warning: "#ebcb8b",
    "warning-foreground": "#ebcb8b",
    "scrollbar-thumb": "rgba(216, 222, 233, 0.16)",
    "scrollbar-thumb-hover": "rgba(216, 222, 233, 0.28)",
    "scrollbar-thumb-thin": "rgba(216, 222, 233, 0.12)",
    "scrollbar-thumb-thin-hover": "rgba(216, 222, 233, 0.22)",
  },
};

const HIGH_CONTRAST: ThemeDefinition = {
  id: "high-contrast",
  name: "High Contrast",
  description: "Maximum-contrast monochrome with yellow accents for accessibility.",
  builtIn: true,
  light: {
    background: "#ffffff",
    "app-chrome-background": "#ffffff",
    foreground: "#000000",
    card: "#ffffff",
    "card-foreground": "#000000",
    popover: "#ffffff",
    "popover-foreground": "#000000",
    primary: "#0000ee",
    "primary-foreground": "#ffffff",
    secondary: "#f5f5f5",
    "secondary-foreground": "#000000",
    muted: "#f0f0f0",
    "muted-foreground": "#1a1a1a",
    accent: "#ffeb3b",
    "accent-foreground": "#000000",
    destructive: "#cc0000",
    "destructive-foreground": "#ffffff",
    border: "#000000",
    input: "#000000",
    ring: "#0000ee",
    info: "#0000ee",
    "info-foreground": "#0000aa",
    success: "#006400",
    "success-foreground": "#003200",
    warning: "#996600",
    "warning-foreground": "#664400",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.55)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.8)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.45)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.7)",
    "noise-opacity": "0",
  },
  dark: {
    background: "#000000",
    "app-chrome-background": "#000000",
    foreground: "#ffffff",
    card: "#000000",
    "card-foreground": "#ffffff",
    popover: "#000000",
    "popover-foreground": "#ffffff",
    primary: "#ffff00",
    "primary-foreground": "#000000",
    secondary: "#1a1a1a",
    "secondary-foreground": "#ffffff",
    muted: "#0d0d0d",
    "muted-foreground": "#e6e6e6",
    accent: "#ffff00",
    "accent-foreground": "#000000",
    destructive: "#ff5555",
    "destructive-foreground": "#000000",
    border: "#ffffff",
    input: "#ffffff",
    ring: "#ffff00",
    info: "#5fd7ff",
    "info-foreground": "#5fd7ff",
    success: "#5fff5f",
    "success-foreground": "#5fff5f",
    warning: "#ffff5f",
    "warning-foreground": "#ffff5f",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.55)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.85)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.4)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.7)",
    "noise-opacity": "0",
  },
};

const ONE_DARK_PRO: ThemeDefinition = {
  id: "one-dark-pro",
  name: "One Dark Pro",
  description: "Atom's One Dark palette adapted from the popular VS Code theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#282c34",
    chrome: "#21252b",
    foreground: "#abb2bf",
    card: "#30333d",
    primary: "#61afef",
    primaryForeground: "#ffffff",
    secondary: "#30333d",
    muted: "#2c313c",
    mutedForeground: "#636b78",
    accent: "#3e4452",
    accentForeground: "#abb2bf",
    destructive: "#e06c75",
    destructiveForeground: "#ffffff",
    border: "#3e4452",
    input: "#1d1f23",
    info: "#56b6c2",
    success: "#98c379",
    warning: "#e5c07b",
  }),
};

const DRACULA: ThemeDefinition = {
  id: "dracula",
  name: "Dracula",
  description: "A dark purple workbench inspired by the Dracula VS Code theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#282A36",
    chrome: "#21222C",
    foreground: "#F8F8F2",
    card: "#343746",
    primary: "#BD93F9",
    primaryForeground: "#282A36",
    secondary: "#44475A",
    muted: "#44475A",
    mutedForeground: "#6272A4",
    accent: "#FF79C6",
    accentForeground: "#282A36",
    destructive: "#FF5555",
    destructiveForeground: "#282A36",
    border: "#191A21",
    input: "#191A21",
    ring: "#6272A4",
    info: "#8BE9FD",
    success: "#50FA7B",
    warning: "#FFB86C",
  }),
};

const GITHUB: ThemeDefinition = {
  id: "github",
  name: "GitHub",
  description: "GitHub Light and Dark palettes adapted from the official VS Code theme.",
  builtIn: true,
  light: presetTokens({
    background: "#ffffff",
    chrome: "#f6f8fa",
    foreground: "#1f2328",
    card: "#ffffff",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    secondary: "#f6f8fa",
    muted: "#f6f8fa",
    mutedForeground: "#656d76",
    accent: "#dbeafe",
    accentForeground: "#0969da",
    destructive: "#cf222e",
    destructiveForeground: "#ffffff",
    border: "#d0d7de",
    input: "#d0d7de",
    info: "#0969da",
    success: "#1f883d",
    warning: "#9a6700",
    scrollbarForeground: "#1f2328",
  }),
  dark: presetTokens({
    background: "#0d1117",
    chrome: "#010409",
    foreground: "#e6edf3",
    card: "#161b22",
    primary: "#2f81f7",
    primaryForeground: "#ffffff",
    secondary: "#21262d",
    muted: "#21262d",
    mutedForeground: "#7d8590",
    accent: "#1f6feb",
    accentForeground: "#ffffff",
    destructive: "#f85149",
    destructiveForeground: "#ffffff",
    border: "#30363d",
    input: "#30363d",
    info: "#2f81f7",
    success: "#3fb950",
    warning: "#d29922",
  }),
};

const CATPPUCCIN: ThemeDefinition = {
  id: "catppuccin",
  name: "Catppuccin",
  description: "Catppuccin Latte and Mocha palettes with a mauve accent.",
  builtIn: true,
  light: presetTokens({
    background: "#eff1f5",
    chrome: "#e6e9ef",
    foreground: "#4c4f69",
    card: "#ffffff",
    primary: "#8839ef",
    primaryForeground: "#ffffff",
    secondary: "#ccd0da",
    muted: "#dce0e8",
    mutedForeground: "#6c6f85",
    accent: "#bcc0cc",
    accentForeground: "#4c4f69",
    destructive: "#d20f39",
    destructiveForeground: "#ffffff",
    border: "#bcc0cc",
    input: "#bcc0cc",
    info: "#1e66f5",
    success: "#40a02b",
    warning: "#df8e1d",
  }),
  dark: presetTokens({
    background: "#1e1e2e",
    chrome: "#181825",
    foreground: "#cdd6f4",
    card: "#313244",
    primary: "#cba6f7",
    primaryForeground: "#1e1e2e",
    secondary: "#313244",
    muted: "#313244",
    mutedForeground: "#a6adc8",
    accent: "#45475a",
    accentForeground: "#cdd6f4",
    destructive: "#f38ba8",
    destructiveForeground: "#1e1e2e",
    border: "#45475a",
    input: "#45475a",
    info: "#89b4fa",
    success: "#a6e3a1",
    warning: "#f9e2af",
  }),
};

const TOKYO_NIGHT: ThemeDefinition = {
  id: "tokyo-night",
  name: "Tokyo Night",
  description: "A deep blue workbench inspired by Enkia's Tokyo Night theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#1a1b26",
    chrome: "#16161e",
    foreground: "#a9b1d6",
    card: "#202330",
    primary: "#7aa2f7",
    primaryForeground: "#ffffff",
    secondary: "#202330",
    muted: "#1c1d29",
    mutedForeground: "#787c99",
    accent: "#3d59a1",
    accentForeground: "#ffffff",
    destructive: "#db4b4b",
    destructiveForeground: "#ffffff",
    border: "#101014",
    input: "#14141b",
    info: "#2ac3de",
    success: "#9ece6a",
    warning: "#e0af68",
  }),
};

const MONOKAI: ThemeDefinition = {
  id: "monokai",
  name: "Monokai",
  description: "Classic Monokai colors with hot pink and green accents.",
  builtIn: true,
  dark: presetTokens({
    background: "#272822",
    chrome: "#1f201b",
    foreground: "#f8f8f2",
    card: "#34352f",
    primary: "#f92672",
    primaryForeground: "#ffffff",
    secondary: "#3e3d32",
    muted: "#3e3d32",
    mutedForeground: "#a59f85",
    accent: "#49483e",
    accentForeground: "#f8f8f2",
    destructive: "#f92672",
    destructiveForeground: "#ffffff",
    border: "#49483e",
    input: "#1f201b",
    info: "#66d9ef",
    success: "#a6e22e",
    warning: "#e6db74",
  }),
};

const GRUVBOX_MATERIAL: ThemeDefinition = {
  id: "gruvbox-material",
  name: "Gruvbox Material",
  description: "Warm low-contrast Gruvbox Material light and dark palettes.",
  builtIn: true,
  light: presetTokens({
    background: "#fbf1c7",
    chrome: "#f2e5bc",
    foreground: "#654735",
    card: "#f9ead3",
    primary: "#7c6f64",
    primaryForeground: "#fbf1c7",
    secondary: "#ebdbb2",
    muted: "#ebdbb2",
    mutedForeground: "#7c6f64",
    accent: "#d5c4a1",
    accentForeground: "#654735",
    destructive: "#c14a4a",
    destructiveForeground: "#fbf1c7",
    border: "#d5c4a1",
    input: "#d5c4a1",
    info: "#45707a",
    success: "#6c782e",
    warning: "#b47109",
  }),
  dark: presetTokens({
    background: "#292828",
    chrome: "#292828",
    foreground: "#d4be98",
    card: "#32302f",
    primary: "#a89984",
    primaryForeground: "#292828",
    secondary: "#383432",
    muted: "#32302f",
    mutedForeground: "#928374",
    accent: "#45403d",
    accentForeground: "#d4be98",
    destructive: "#ea6962",
    destructiveForeground: "#292828",
    border: "#45403d",
    input: "#45403d",
    info: "#7daea3",
    success: "#a9b665",
    warning: "#d8a657",
  }),
};

const CURSOR_DARK_INSPIRED: ThemeDefinition = {
  id: "cursor-dark-inspired",
  name: "Cursor Dark Inspired",
  description: "A restrained dark editor palette inspired by Cursor's VS Code-compatible UI.",
  builtIn: true,
  dark: presetTokens({
    background: "#171717",
    chrome: "#101010",
    foreground: "#d4d4d4",
    card: "#1f1f1f",
    primary: "#8ab4ff",
    primaryForeground: "#0b0b0b",
    secondary: "#272727",
    muted: "#222222",
    mutedForeground: "#858585",
    accent: "#333333",
    accentForeground: "#d4d4d4",
    destructive: "#f87171",
    destructiveForeground: "#0b0b0b",
    border: "#333333",
    input: "#2b2b2b",
    info: "#7dd3fc",
    success: "#86efac",
    warning: "#facc15",
  }),
};

export const BUILT_IN_THEMES: readonly ThemeDefinition[] = [
  DEFAULT_THEME,
  SOLARIZED_DARK,
  NORD,
  HIGH_CONTRAST,
  ONE_DARK_PRO,
  DRACULA,
  GITHUB,
  CATPPUCCIN,
  TOKYO_NIGHT,
  MONOKAI,
  GRUVBOX_MATERIAL,
  CURSOR_DARK_INSPIRED,
];
