import type { ThemeDefinition, ThemeTokens } from "./types";

export const DEFAULT_THEME_ID = "default";

export const DEFAULT_THEME: ThemeDefinition = {
  id: DEFAULT_THEME_ID,
  name: "Default",
  description: "The built-in Ryco light & dark palette.",
  builtIn: true,
  light: {
    background: "var(--color-white)",
    "app-chrome-background": "var(--background)",
    foreground: "var(--color-neutral-800)",
    card: "var(--color-white)",
    "card-foreground": "var(--color-neutral-800)",
    popover: "var(--color-white)",
    "popover-foreground": "var(--color-neutral-800)",
    primary: "var(--color-neutral-900)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-black) / 5%)",
    "secondary-foreground": "var(--color-neutral-800)",
    muted: "--alpha(var(--color-black) / 4.5%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-black))",
    accent: "--alpha(var(--color-black) / 6.5%)",
    "accent-foreground": "var(--color-neutral-900)",
    destructive: "var(--color-red-500)",
    "destructive-foreground": "var(--color-red-700)",
    border: "--alpha(var(--color-black) / 10%)",
    input: "--alpha(var(--color-black) / 12%)",
    ring: "var(--color-neutral-600)",
    sidebar: "color-mix(in srgb, var(--color-black) 3%, var(--background))",
    "sidebar-foreground": "var(--foreground)",
    "sidebar-border": "--alpha(var(--color-black) / 7%)",
    "sidebar-accent": "--alpha(var(--color-black) / 5%)",
    "sidebar-accent-foreground": "var(--foreground)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-700)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-700)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-700)",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.15)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.25)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.1)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.2)",
    "noise-opacity": "0.035",
  },
  dark: {
    background: "#0b0b0c",
    "app-chrome-background": "var(--background)",
    foreground: "#ececed",
    card: "color-mix(in srgb, var(--background) 96%, var(--color-white))",
    "card-foreground": "var(--foreground)",
    popover: "color-mix(in srgb, var(--background) 94%, var(--color-white))",
    "popover-foreground": "var(--foreground)",
    primary: "#e4e4e5",
    "primary-foreground": "#0b0b0c",
    secondary: "--alpha(var(--color-white) / 7%)",
    "secondary-foreground": "var(--foreground)",
    muted: "--alpha(var(--color-white) / 6%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-400) 82%, var(--color-white))",
    accent: "--alpha(var(--color-white) / 9%)",
    "accent-foreground": "#f4f4f5",
    destructive: "color-mix(in srgb, var(--color-red-500) 90%, var(--color-white))",
    "destructive-foreground": "var(--color-red-400)",
    border: "--alpha(var(--color-white) / 9%)",
    input: "--alpha(var(--color-white) / 12%)",
    ring: "#a1a1a6",
    sidebar: "color-mix(in srgb, var(--color-black) 34%, var(--background))",
    "sidebar-foreground": "var(--foreground)",
    "sidebar-border": "--alpha(var(--color-white) / 7%)",
    "sidebar-accent": "--alpha(var(--color-white) / 8%)",
    "sidebar-accent-foreground": "var(--foreground)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-400)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-400)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-400)",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.1)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.18)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.08)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.15)",
  },
};

type PresetPalette = {
  background: string;
  chrome: string;
  foreground: string;
  card: string;
  popover?: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  ring?: string;
  info: string;
  success: string;
  warning: string;
  scrollbarForeground?: string;
};

function presetTokens(palette: PresetPalette): ThemeTokens {
  const scrollbarBase = palette.scrollbarForeground ?? palette.foreground;
  return {
    background: palette.background,
    "app-chrome-background": palette.chrome,
    foreground: palette.foreground,
    card: palette.card,
    "card-foreground": palette.foreground,
    popover: palette.popover ?? palette.card,
    "popover-foreground": palette.foreground,
    primary: palette.primary,
    "primary-foreground": palette.primaryForeground,
    secondary: palette.secondary,
    "secondary-foreground": palette.foreground,
    muted: palette.muted,
    "muted-foreground": palette.mutedForeground,
    accent: palette.accent,
    "accent-foreground": palette.accentForeground,
    destructive: palette.destructive,
    "destructive-foreground": palette.destructiveForeground,
    border: palette.border,
    input: palette.input,
    ring: palette.ring ?? palette.primary,
    info: palette.info,
    "info-foreground": palette.info,
    success: palette.success,
    "success-foreground": palette.success,
    warning: palette.warning,
    "warning-foreground": palette.warning,
    "scrollbar-thumb": hexToRgba(scrollbarBase, 0.18),
    "scrollbar-thumb-hover": hexToRgba(scrollbarBase, 0.32),
    "scrollbar-thumb-thin": hexToRgba(scrollbarBase, 0.12),
    "scrollbar-thumb-thin-hover": hexToRgba(scrollbarBase, 0.24),
  };
}

function hexToRgba(hex: string, alpha: number): string {
  const match = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!match || match[1] === undefined) return hex;
  const value = match[1];
  const r = Number.parseInt(value.slice(0, 2), 16);
  const g = Number.parseInt(value.slice(2, 4), 16);
  const b = Number.parseInt(value.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const NORD: ThemeDefinition = {
  id: "nord",
  name: "Nord",
  description: "Cool arctic blues inspired by the Nord palette by Arctic Ice Studio.",
  builtIn: true,
  dark: {
    background: "#2e3440",
    "app-chrome-background": "#2e3440",
    foreground: "#d8dee9",
    card: "#3b4252",
    "card-foreground": "#e5e9f0",
    popover: "#3b4252",
    "popover-foreground": "#e5e9f0",
    primary: "#88c0d0",
    "primary-foreground": "#2e3440",
    secondary: "#434c5e",
    "secondary-foreground": "#e5e9f0",
    muted: "#3b4252",
    "muted-foreground": "#7b8794",
    accent: "#434c5e",
    "accent-foreground": "#eceff4",
    destructive: "#bf616a",
    "destructive-foreground": "#eceff4",
    border: "rgba(216, 222, 233, 0.1)",
    input: "rgba(216, 222, 233, 0.14)",
    ring: "#88c0d0",
    info: "#81a1c1",
    "info-foreground": "#8fbcbb",
    success: "#a3be8c",
    "success-foreground": "#a3be8c",
    warning: "#ebcb8b",
    "warning-foreground": "#ebcb8b",
    "scrollbar-thumb": "rgba(216, 222, 233, 0.16)",
    "scrollbar-thumb-hover": "rgba(216, 222, 233, 0.28)",
    "scrollbar-thumb-thin": "rgba(216, 222, 233, 0.12)",
    "scrollbar-thumb-thin-hover": "rgba(216, 222, 233, 0.22)",
  },
};

const HIGH_CONTRAST: ThemeDefinition = {
  id: "high-contrast",
  name: "High Contrast",
  description: "Maximum-contrast monochrome with yellow accents for accessibility.",
  builtIn: true,
  light: {
    background: "#ffffff",
    "app-chrome-background": "#ffffff",
    foreground: "#000000",
    card: "#ffffff",
    "card-foreground": "#000000",
    popover: "#ffffff",
    "popover-foreground": "#000000",
    primary: "#0000ee",
    "primary-foreground": "#ffffff",
    secondary: "#f5f5f5",
    "secondary-foreground": "#000000",
    muted: "#f0f0f0",
    "muted-foreground": "#1a1a1a",
    accent: "#ffeb3b",
    "accent-foreground": "#000000",
    destructive: "#cc0000",
    "destructive-foreground": "#ffffff",
    border: "#000000",
    input: "#000000",
    ring: "#0000ee",
    info: "#0000ee",
    "info-foreground": "#0000aa",
    success: "#006400",
    "success-foreground": "#003200",
    warning: "#996600",
    "warning-foreground": "#664400",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.55)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.8)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.45)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.7)",
    "noise-opacity": "0",
  },
  dark: {
    background: "#000000",
    "app-chrome-background": "#000000",
    foreground: "#ffffff",
    card: "#000000",
    "card-foreground": "#ffffff",
    popover: "#000000",
    "popover-foreground": "#ffffff",
    primary: "#ffff00",
    "primary-foreground": "#000000",
    secondary: "#1a1a1a",
    "secondary-foreground": "#ffffff",
    muted: "#0d0d0d",
    "muted-foreground": "#e6e6e6",
    accent: "#ffff00",
    "accent-foreground": "#000000",
    destructive: "#ff5555",
    "destructive-foreground": "#000000",
    border: "#ffffff",
    input: "#ffffff",
    ring: "#ffff00",
    info: "#5fd7ff",
    "info-foreground": "#5fd7ff",
    success: "#5fff5f",
    "success-foreground": "#5fff5f",
    warning: "#ffff5f",
    "warning-foreground": "#ffff5f",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.55)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.85)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.4)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.7)",
    "noise-opacity": "0",
  },
};

const MIDNIGHT_GRAPHITE: ThemeDefinition = {
  id: "midnight-graphite",
  name: "Midnight Graphite",
  description: "A near-black graphite palette with neutral grey actions.",
  builtIn: true,
  dark: {
    ...presetTokens({
      background: "#040404",
      chrome: "#020202",
      foreground: "#e7e7e7",
      card: "#0a0a0a",
      popover: "#0d0d0d",
      primary: "#d4d4d4",
      primaryForeground: "#030303",
      secondary: "#111111",
      muted: "#0d0d0d",
      mutedForeground: "#777777",
      accent: "#151515",
      accentForeground: "#eeeeee",
      destructive: "#ef4444",
      destructiveForeground: "#f87171",
      border: "rgba(255, 255, 255, 0.075)",
      input: "rgba(255, 255, 255, 0.11)",
      ring: "#b8b8b8",
      info: "#b0b0b0",
      success: "#22c55e",
      warning: "#c4a760",
      scrollbarForeground: "#d4d4d4",
    }),
    "noise-opacity": "0.012",
  },
};

const ONE_DARK_PRO: ThemeDefinition = {
  id: "one-dark-pro",
  name: "One Dark Pro",
  description: "Atom's One Dark palette adapted from the popular VS Code theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#282c34",
    chrome: "#21252b",
    foreground: "#abb2bf",
    card: "#30333d",
    primary: "#61afef",
    primaryForeground: "#ffffff",
    secondary: "#30333d",
    muted: "#2c313c",
    mutedForeground: "#636b78",
    accent: "#3e4452",
    accentForeground: "#abb2bf",
    destructive: "#e06c75",
    destructiveForeground: "#ffffff",
    border: "#3e4452",
    input: "#1d1f23",
    info: "#56b6c2",
    success: "#98c379",
    warning: "#e5c07b",
  }),
};

const DRACULA: ThemeDefinition = {
  id: "dracula",
  name: "Dracula",
  description: "A dark purple workbench inspired by the Dracula VS Code theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#282A36",
    chrome: "#21222C",
    foreground: "#F8F8F2",
    card: "#343746",
    primary: "#BD93F9",
    primaryForeground: "#282A36",
    secondary: "#44475A",
    muted: "#44475A",
    mutedForeground: "#6272A4",
    accent: "#FF79C6",
    accentForeground: "#282A36",
    destructive: "#FF5555",
    destructiveForeground: "#282A36",
    border: "#191A21",
    input: "#191A21",
    ring: "#6272A4",
    info: "#8BE9FD",
    success: "#50FA7B",
    warning: "#FFB86C",
  }),
};

const GITHUB: ThemeDefinition = {
  id: "github",
  name: "GitHub",
  description: "GitHub Light and Dark palettes adapted from the official VS Code theme.",
  builtIn: true,
  light: presetTokens({
    background: "#ffffff",
    chrome: "#f6f8fa",
    foreground: "#1f2328",
    card: "#ffffff",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    secondary: "#f6f8fa",
    muted: "#f6f8fa",
    mutedForeground: "#656d76",
    accent: "#dbeafe",
    accentForeground: "#0969da",
    destructive: "#cf222e",
    destructiveForeground: "#ffffff",
    border: "#d0d7de",
    input: "#d0d7de",
    info: "#0969da",
    success: "#1f883d",
    warning: "#9a6700",
    scrollbarForeground: "#1f2328",
  }),
  dark: presetTokens({
    background: "#0d1117",
    chrome: "#010409",
    foreground: "#e6edf3",
    card: "#161b22",
    primary: "#2f81f7",
    primaryForeground: "#ffffff",
    secondary: "#21262d",
    muted: "#21262d",
    mutedForeground: "#7d8590",
    accent: "#1f6feb",
    accentForeground: "#ffffff",
    destructive: "#f85149",
    destructiveForeground: "#ffffff",
    border: "#30363d",
    input: "#30363d",
    info: "#2f81f7",
    success: "#3fb950",
    warning: "#d29922",
  }),
};

const CATPPUCCIN: ThemeDefinition = {
  id: "catppuccin",
  name: "Catppuccin",
  description: "Catppuccin Latte and Mocha palettes with a mauve accent.",
  builtIn: true,
  light: presetTokens({
    background: "#eff1f5",
    chrome: "#e6e9ef",
    foreground: "#4c4f69",
    card: "#ffffff",
    primary: "#8839ef",
    primaryForeground: "#ffffff",
    secondary: "#ccd0da",
    muted: "#dce0e8",
    mutedForeground: "#6c6f85",
    accent: "#bcc0cc",
    accentForeground: "#4c4f69",
    destructive: "#d20f39",
    destructiveForeground: "#ffffff",
    border: "#bcc0cc",
    input: "#bcc0cc",
    info: "#1e66f5",
    success: "#40a02b",
    warning: "#df8e1d",
  }),
  dark: presetTokens({
    background: "#1e1e2e",
    chrome: "#181825",
    foreground: "#cdd6f4",
    card: "#313244",
    primary: "#cba6f7",
    primaryForeground: "#1e1e2e",
    secondary: "#313244",
    muted: "#313244",
    mutedForeground: "#a6adc8",
    accent: "#45475a",
    accentForeground: "#cdd6f4",
    destructive: "#f38ba8",
    destructiveForeground: "#1e1e2e",
    border: "#45475a",
    input: "#45475a",
    info: "#89b4fa",
    success: "#a6e3a1",
    warning: "#f9e2af",
  }),
};

const TOKYO_NIGHT: ThemeDefinition = {
  id: "tokyo-night",
  name: "Tokyo Night",
  description: "A deep blue workbench inspired by Enkia's Tokyo Night theme.",
  builtIn: true,
  dark: presetTokens({
    background: "#1a1b26",
    chrome: "#16161e",
    foreground: "#a9b1d6",
    card: "#202330",
    primary: "#7aa2f7",
    primaryForeground: "#ffffff",
    secondary: "#202330",
    muted: "#1c1d29",
    mutedForeground: "#787c99",
    accent: "#3d59a1",
    accentForeground: "#ffffff",
    destructive: "#db4b4b",
    destructiveForeground: "#ffffff",
    border: "#101014",
    input: "#14141b",
    info: "#2ac3de",
    success: "#9ece6a",
    warning: "#e0af68",
  }),
};

export const BUILT_IN_THEMES: readonly ThemeDefinition[] = [
  DEFAULT_THEME,
  MIDNIGHT_GRAPHITE,
  NORD,
  HIGH_CONTRAST,
  ONE_DARK_PRO,
  DRACULA,
  GITHUB,
  CATPPUCCIN,
  TOKYO_NIGHT,
];
