import type { ServerConfigShape } from "../config.ts";

export const makeTestServerConfig = (
  overrides: Partial<ServerConfigShape> = {},
): ServerConfigShape => ({
  logLevel: "Error",
  traceMinLevel: "Info",
  traceTimingEnabled: true,
  traceBatchWindowMs: 200,
  traceMaxBytes: 10 * 1024 * 1024,
  traceMaxFiles: 10,
  otlpTracesUrl: undefined,
  otlpMetricsUrl: undefined,
  otlpExportIntervalMs: 10_000,
  otlpServiceName: "ryco-server-test",
  mode: "desktop",
  port: 3773,
  host: "127.0.0.1",
  cwd: "/tmp/ryco-test",
  baseDir: "/tmp/ryco-test",
  staticDir: undefined,
  devUrl: undefined,
  noBrowser: true,
  startupPresentation: "browser",
  desktopBootstrapToken: undefined,
  desktopBrowserHostToken: "secret-token",
  autoBootstrapProjectFromCwd: false,
  logWebSocketEvents: false,
  tailscaleServeEnabled: false,
  tailscaleServePort: 443,
  stateDir: "/tmp/ryco-test/state",
  dbPath: "/tmp/ryco-test/state/state.sqlite",
  keybindingsConfigPath: "/tmp/ryco-test/state/keybindings.json",
  settingsPath: "/tmp/ryco-test/state/settings.json",
  providerStatusCacheDir: "/tmp/ryco-test/caches",
  worktreesDir: "/tmp/ryco-test/worktrees",
  attachmentsDir: "/tmp/ryco-test/state/attachments",
  logsDir: "/tmp/ryco-test/state/logs",
  serverLogPath: "/tmp/ryco-test/state/logs/server.log",
  serverTracePath: "/tmp/ryco-test/state/logs/server.trace.ndjson",
  providerLogsDir: "/tmp/ryco-test/state/logs/provider",
  providerEventLogPath: "/tmp/ryco-test/state/logs/provider/events.log",
  terminalLogsDir: "/tmp/ryco-test/state/logs/terminals",
  anonymousIdPath: "/tmp/ryco-test/state/anonymous-id",
  environmentIdPath: "/tmp/ryco-test/state/environment-id",
  serverRuntimeStatePath: "/tmp/ryco-test/state/server-runtime.json",
  secretsDir: "/tmp/ryco-test/state/secrets",
  ...overrides,
});
