export {
  getPrimaryKnownEnvironment,
  readPrimaryEnvironmentDescriptor,
  resetPrimaryEnvironmentDescriptorForTests,
  resolveInitialPrimaryEnvironmentDescriptor,
  usePrimaryEnvironmentId,
  writePrimaryEnvironmentDescriptor,
  __resetPrimaryEnvironmentBootstrapForTests,
  __resetPrimaryEnvironmentDescriptorBootstrapForTests,
} from "./context";

export {
  resolveInitialPrimaryEnvironmentDescriptor as ensurePrimaryEnvironmentReady,
  writePrimaryEnvironmentDescriptor as updatePrimaryEnvironmentDescriptor,
} from "./context";

export {
  applyNodeE2eeAuthorization,
  applyNodeE2eeContinuity,
  applyNodeE2eePolicy,
  cancelHubEnrollment,
  clearNodeE2eeRefusals,
  createServerPairingCredential,
  fetchHubEnrollment,
  fetchHubIdentity,
  fetchHubStatus,
  fetchNodeE2eeClients,
  fetchNodeE2eeContinuity,
  fetchNodeE2eeFallback,
  fetchNodeE2eePolicy,
  fetchNodeE2eePrekey,
  fetchNodeE2eeSessions,
  fetchSessionState,
  leaveHub,
  previewNodeE2eePolicy,
  recoverNodeE2eePolicyGeneration,
  resetNodeE2eeFallback,
  resumeHubConnector,
  rotateNodeE2eePrekey,
  setNodeE2eePairingWindow,
  startHubEnrollment,
  issuePrimaryWebSocketToken,
  listServerClientSessions,
  listServerPairingLinks,
  peekPairingTokenFromUrl,
  resolveInitialServerAuthGateState,
  revokeOtherServerClientSessions,
  revokeServerClientSession,
  revokeServerPairingLink,
  stripPairingTokenFromUrl,
  submitServerAuthCredential,
  takePairingTokenFromUrl,
  type ServerClientSessionRecord,
  type ServerPairingLinkRecord,
  __resetServerAuthBootstrapForTests,
} from "./auth";

export { resolvePrimaryEnvironmentHttpUrl, isLoopbackHostname } from "./target";
