const fs = require("node:fs/promises");
const path = require("node:path");

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require("expo/config-plugins");

// docs/relay-e2ee-protocol.md §6.3 requires the native client's agreement-key
// entry to be "excluded from every backup and transfer surface" on Android.
//
// WHY THIS CANNOT BE DONE FROM JAVASCRIPT. expo-secure-store's Android options
// are only `authenticationPrompt`, `keychainService`, and `requireAuthentication`
// (`SecureStoreOptions.kt`), and the ciphertext it writes lands in an ordinary
// SharedPreferences file — `getSharedPreferences("SecureStore", MODE_PRIVATE)`,
// i.e. `shared_prefs/SecureStore.xml`. Android backs that file up unless the app
// says otherwise, and only the manifest can say otherwise.
//
// WHY A TARGETED EXCLUSION AND NOT `allowBackup="false"`. Turning backup off for
// the whole app would also stop backing up the saved-environment registry and the
// hub profile, which are ordinary user data with no such requirement. Excluding
// exactly the one file leaves the rest of the app's backup behaviour untouched.
//
// WHY NOT EXPO'S OWN RULES. expo-secure-store ships `secure_store_backup_rules`
// and `secure_store_data_extraction_rules`, and this app opts out of them
// (`configureAndroidBackup: false` in app.config.ts) for two reasons. They open
// with `<include domain="sharedpref" path="."/>`, and an `<include>` makes the
// rules an allow-list — everything outside `sharedpref`, which here is the
// SQLite-backed environment registry and the hub profile, would stop being backed
// up at all. And they exclude `path="SecureStore"`, without the extension the
// file actually has.
//
// BOTH SPELLINGS ARE EXCLUDED, deliberately. The backup engine matches an
// excluded path against the files it walks, and the file it walks is
// `shared_prefs/SecureStore.xml`; whether the extension-less form also matches
// depends on engine behaviour this repository cannot verify from a build. Listing
// both costs nothing — an entry that matches no file simply never fires — and
// leaves no version of that question able to expose the key.
//
// BOTH FILES ARE REQUIRED. `android:fullBackupContent` governs API 30 and below;
// `android:dataExtractionRules` governs API 31 and above and splits cloud backup
// from device transfer, so §6.3's "backup, restore, AND device-transfer" needs
// both of its sections. Authoring only one leaves the other era unprotected.
//
// The AndroidKeyStore key that encrypts the entry is itself non-exportable, so a
// restored preferences file would be undecryptable in any case. That is a second
// line, not this one: §6.3 asks for the material to be unavailable to backup and
// transfer surfaces in the first place.

const BACKUP_RULES_RESOURCE = "ryco_e2ee_backup_rules";
const DATA_EXTRACTION_RULES_RESOURCE = "ryco_e2ee_data_extraction_rules";

/** `SecureStoreModule.SHARED_PREFERENCES_NAME`, as the backup domain sees it. */
const SECURE_STORE_PREFERENCES_PATHS = ["SecureStore.xml", "SecureStore"];

function excludes(indent) {
  return SECURE_STORE_PREFERENCES_PATHS.map(
    (path) => `${indent}<exclude domain="sharedpref" path="${path}" />`,
  ).join("\n");
}

const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecureStoreBackupExclusion.cjs. Edit the plugin. -->
<full-backup-content>
${excludes("  ")}
</full-backup-content>
`;

const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecureStoreBackupExclusion.cjs. Edit the plugin. -->
<data-extraction-rules>
  <cloud-backup>
${excludes("    ")}
  </cloud-backup>
  <device-transfer>
${excludes("    ")}
  </device-transfer>
</data-extraction-rules>
`;

module.exports = function withAndroidSecureStoreBackupExclusion(config) {
  const withRules = withDangerousMod(config, [
    "android",
    async (nextConfig) => {
      const resourceFolder = await AndroidConfig.Paths.getResourceFolderAsync(
        nextConfig.modRequest.projectRoot,
      );
      const xmlFolder = path.join(resourceFolder, "xml");
      await fs.mkdir(xmlFolder, { recursive: true });
      await fs.writeFile(
        path.join(xmlFolder, `${BACKUP_RULES_RESOURCE}.xml`),
        BACKUP_RULES_XML,
        "utf8",
      );
      await fs.writeFile(
        path.join(xmlFolder, `${DATA_EXTRACTION_RULES_RESOURCE}.xml`),
        DATA_EXTRACTION_RULES_XML,
        "utf8",
      );
      return nextConfig;
    },
  ]);

  return withAndroidManifest(withRules, (nextConfig) => {
    const application = nextConfig.modResults.manifest.application?.[0];

    if (application == null) {
      throw new Error(
        "AndroidManifest.xml is missing the application element required for the SecureStore backup exclusion.",
      );
    }

    application.$ ??= {};
    application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_RESOURCE}`;
    application.$["android:dataExtractionRules"] = `@xml/${DATA_EXTRACTION_RULES_RESOURCE}`;

    return nextConfig;
  });
};
