export const PROVIDER_STATUS_DEBOUNCE_MS = 200;
export const SOURCE_CONTROL_LINKED_REFRESH_DEBOUNCE_MS = 5_000;
export const ORCHESTRATION_REPLAY_PAGE_MAX_LIMIT = 1_000;
export const ORCHESTRATION_LEGACY_REPLAY_MAX_EVENTS = ORCHESTRATION_REPLAY_PAGE_MAX_LIMIT;
export const ORCHESTRATION_LIVE_QUEUE_MAX_EVENTS = 1_000;
